### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by FabulousCodingFox** [shepherdjerred/astro-opengraph-images#25]
`handlePage` takes the URL parameter "dir" without properly converting it to a file path. This results in an incompatibility with filesystems that dont begin the root path with a "/" char.

All URL objects should be converted to an absolute file path using fileURLToPath from the url package included with node.

See https://github.com/withastro/astro/issues/3607

**Comment by shepherdjerred** [comment]
Thank you for adding this.

**Comment by shepherdjerred** [comment]
This is released as part of 1.7.0. It should be on npm shortly.
