### ISSUE TITLE
feature-request for extra page-parameters

### ISSUE THREAD

**Issue by melistik** [shepherdjerred/astro-opengraph-images#63]
Your library works very well but asper my understanding you can only pass values to the rendering-function that have been "rendered" already to the dom... For title, description url etc. you have already implemented and extract function that parse over these values...

do you see an option to extend your api in that case so that i can hand over page-specific background-images for example so that the og:images vary a lot more instead of a fixed layout... I could already create a custom-meta tag that i can read by document.querySelector but could i would prefer to access frontMatter parameters or something else but howto? Should a reread the file and extract frontMatter values? I don't have any clue.

thx in advance

**Comment by shepherdjerred** [comment]
Hi @melistik, do you still need any help with this?

**Comment by melistik** [comment]
Hi @shepherdjerred thx for your help - now i understand the flow - thank your very much for your help
