### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Mad-Kat** [shepherdjerred/astro-opengraph-images#71]
I get the this type error during build:
```sh
[astro-opengraph-images] TypeError: t is not iterable
```

This is my config:

```mjs
opengraphImages({
  options: {
    fonts: {
      name: "Diatype",
      weight: "Variable",
      style: "Regular",
      data: fs.readFileSync("public/fonts/diatype-variable.ttf"),
    },
  },
  render: ogMediaLayout,
})
```

Could it be because of the variable font?

**Comment by Mad-Kat** [comment]
Looks like satori doesn't work with variable fonts atm: [Satori issue](https://github.com/vercel/satori/issues/162)

**Comment by shepherdjerred** [comment]
Thanks for looking into this. Since this isn't an issue with this library, I'm going to close this. I keep dependencies up-to-date, so support will be added soon after Satori adds this functionality.
